/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuadmin.tampilan;

import static uas.Register.main;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import uas.Koneksi;

/**
 *
 * @author adhwa
 */
public class admindatauser extends javax.swing.JFrame {

    users u = new users();

    /**
     * Creates new form admin
     */
    public admindatauser() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);   //melakukan layar full
        this.setUndecorated(true);
        initComponents();
        tampilkanData();
    }
    
    private void tampilkanData() {
        try {
            // Hubungkan ke database
            Koneksi db = new Koneksi();
            Connection conn = db.connect();

            // Query untuk mengambil data dari tabel users
            String sql = "SELECT id_user, username, email, role, nomor_telepon, alamat FROM users";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            // Buat model untuk JTable
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID User");
            model.addColumn("Username");
            model.addColumn("Email");
            model.addColumn("Role");
            model.addColumn("No Telp");
            model.addColumn("Alamat");

            // Loop hasil query dan tambahkan ke model
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_user"),
                    rs.getString("username"),
                    rs.getString("email"),
                    rs.getString("role"),
                    rs.getString("nomor_telepon"),
                    rs.getString("alamat")
                });
            }

            // Set model ke JTable
            tabeluser.setModel(model);

            // Tutup koneksi
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + ex.getMessage());
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialColor1 = new efectos.MaterialColor();
        pnback = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        exit15 = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        btndataadmin = new rojerusan.RSButtonIconD();
        rSButtonIconD2 = new rojerusan.RSButtonIconD();
        btnedituser = new rojerusan.RSButtonIconD();
        btnhapustuser = new rojerusan.RSButtonIconD();
        btntambahtuser = new rojerusan.RSButtonIconD();
        mainpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeluser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(1279, 646));

        pnback.setBackground(new java.awt.Color(255, 255, 255));
        pnback.setPreferredSize(new java.awt.Dimension(1279, 646));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 245, 228));
        kGradientPanel1.setkGradientFocus(900);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 227, 225));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5);
        flowLayout1.setAlignOnBaseline(true);
        kGradientPanel1.setLayout(flowLayout1);

        exit15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit15.setText("X");
        exit15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit15MouseClicked(evt);
            }
        });
        kGradientPanel1.add(exit15);

        kGradientPanel2.setkEndColor(new java.awt.Color(204, 204, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 204, 204));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndataadmin.setBackground(new java.awt.Color(255, 148, 148));
        btndataadmin.setText("Data User");
        btndataadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndataadminActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btndataadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, -1));

        rSButtonIconD2.setBackground(new java.awt.Color(255, 153, 153));
        rSButtonIconD2.setText("Data Produk");
        rSButtonIconD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconD2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSButtonIconD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));

        btnedituser.setBackground(new java.awt.Color(255, 153, 153));
        btnedituser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menuadmin/gambar/icons8-edit-25.png"))); // NOI18N
        btnedituser.setText("Edit");
        btnedituser.setColorHover(new java.awt.Color(255, 204, 204));
        btnedituser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedituserActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnedituser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 150, 40));

        btnhapustuser.setBackground(new java.awt.Color(255, 153, 153));
        btnhapustuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menuadmin/gambar/icons8-delete-24.png"))); // NOI18N
        btnhapustuser.setText("Hapus");
        btnhapustuser.setColorHover(new java.awt.Color(255, 204, 204));
        btnhapustuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapustuserActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnhapustuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 150, -1));

        btntambahtuser.setBackground(new java.awt.Color(255, 153, 153));
        btntambahtuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menuadmin/gambar/icons8-create-24.png"))); // NOI18N
        btntambahtuser.setText("Tambah");
        btntambahtuser.setColorHover(new java.awt.Color(255, 204, 204));
        btntambahtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahtuserActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btntambahtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 150, -1));

        mainpanel.setLayout(new java.awt.CardLayout());

        tabeluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Produk", "Nama Produk", "Title 3", "Title 4"
            }
        ));
        tabeluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeluserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeluser);

        mainpanel.add(jScrollPane1, "card2");

        javax.swing.GroupLayout pnbackLayout = new javax.swing.GroupLayout(pnback);
        pnback.setLayout(pnbackLayout);
        pnbackLayout.setHorizontalGroup(
            pnbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbackLayout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE))
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnbackLayout.setVerticalGroup(
            pnbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbackLayout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(pnback, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndataadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndataadminActionPerformed
    admindatauser u = new admindatauser();
        u.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btndataadminActionPerformed

    private void rSButtonIconD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconD2ActionPerformed
    admindataproduk p = new admindataproduk();
        p.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_rSButtonIconD2ActionPerformed

    private void exit15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit15MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit15MouseClicked

    private void tabeluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeluserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabeluserMouseClicked

    private void btnedituserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedituserActionPerformed
        try {
            // Pastikan ada baris yang dipilih
            int row = tabeluser.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Pilih data yang akan diedit!");
                return;
            }

            // Ambil data dari tabel
            String idUser = tabeluser.getValueAt(row, 0).toString();
            String currentUsername = tabeluser.getValueAt(row, 1).toString();
            String currentEmail = tabeluser.getValueAt(row, 2).toString();
            String currentRole = tabeluser.getValueAt(row, 3).toString();
            String currentNoTelp = tabeluser.getValueAt(row, 4).toString();
            String currentAlamat = tabeluser.getValueAt(row, 5).toString();

            // Ambil input baru dari pengguna
            String newUsername = JOptionPane.showInputDialog(this, "Edit Username:", currentUsername);
            if (newUsername == null || newUsername.trim().isEmpty()) {
                return;
            }

            String newEmail = JOptionPane.showInputDialog(this, "Edit Email:", currentEmail);
            if (newEmail == null || newEmail.trim().isEmpty() || !newEmail.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
                return;
            }

            String newRole = JOptionPane.showInputDialog(this, "Edit Role (admin/customer):", currentRole);
            if (newRole == null || (!newRole.equalsIgnoreCase("admin") && !newRole.equalsIgnoreCase("customer"))) {
                return;
            }

            String newNoTelp = JOptionPane.showInputDialog(this, "Edit Nomor Telepon:", currentNoTelp);
            if (newNoTelp == null || newNoTelp.trim().isEmpty() || !newNoTelp.matches("\\d+")) {
                return;
            }

            String newAlamat = JOptionPane.showInputDialog(this, "Edit Alamat:", currentAlamat);
            if (newAlamat == null || newAlamat.trim().isEmpty()) {
                return;
            }

            // Hubungkan ke database
            Koneksi db = new Koneksi();
            Connection conn = db.connect();

            // Query untuk mengupdate data
            String sql = "UPDATE users SET username = ?, email = ?, role = ?, nomor_telepon = ?, alamat = ? WHERE id_user = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);

            // Isi parameter query
            stmt.setString(1, newUsername);
            stmt.setString(2, newEmail);
            stmt.setString(3, newRole.toLowerCase());
            stmt.setString(4, newNoTelp);
            stmt.setString(5, newAlamat);
            stmt.setString(6, idUser);

            // Eksekusi query
            stmt.executeUpdate();

            // Tampilkan pesan sukses
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");

            // Refresh tabel
            tampilkanData();

            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnedituserActionPerformed

    private void btnhapustuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapustuserActionPerformed
        try {
            // Pastikan ada baris yang dipilih
            int row = tabeluser.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
                return;
            }

            // Ambil ID User dari tabel
            String idUser = tabeluser.getValueAt(row, 0).toString();

            // Konfirmasi penghapusan
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Hubungkan ke database
                Koneksi db = new Koneksi();
                Connection conn = db.connect();

                // Query untuk menghapus data
                String sql = "DELETE FROM users WHERE id_user = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, idUser);

                // Eksekusi query
                stmt.executeUpdate();

                // Tampilkan pesan sukses
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");

                // Refresh tabel
                tampilkanData();

                conn.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnhapustuserActionPerformed

    private void btntambahtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahtuserActionPerformed
        try {
            // Ambil input dari pengguna melalui dialog JOptionPane
            String username = JOptionPane.showInputDialog(this, "Masukkan Username:");
            if (username == null || username.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!");
                return;
            }

            String password = JOptionPane.showInputDialog(this, "Masukkan Password:");
            if (password == null || password.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!");
                return;
            }

            String email = JOptionPane.showInputDialog(this, "Masukkan Email:");
            if (email == null || email.trim().isEmpty() || !email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
                JOptionPane.showMessageDialog(this, "Email tidak valid!");
                return;
            }

            String role = JOptionPane.showInputDialog(this, "Masukkan Role (admin/customer):");
            if (role == null || role.trim().isEmpty() || (!role.equalsIgnoreCase("admin") && !role.equalsIgnoreCase("customer"))) {
                JOptionPane.showMessageDialog(this, "Role harus 'admin' atau 'customer'!");
                return;
            }

            String nomorTelepon = JOptionPane.showInputDialog(this, "Masukkan Nomor Telepon:");
            if (nomorTelepon == null || nomorTelepon.trim().isEmpty() || !nomorTelepon.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Nomor telepon tidak valid!");
                return;
            }

            String alamat = JOptionPane.showInputDialog(this, "Masukkan Alamat:");
            if (alamat == null || alamat.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong!");
                return;
            }

            // Hubungkan ke database
            Koneksi db = new Koneksi();
            Connection conn = db.connect();

            // Query untuk menambahkan data baru
            String sql = "INSERT INTO users (id_user, username, password, email, role, nomor_telepon, alamat) VALUES (?, ?, MD5(?), ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);

            // Generate ID User
            String idUser = "U" + String.format("%03d", (int) (Math.random() * 1000));

            // Isi parameter query
            stmt.setString(1, idUser);
            stmt.setString(2, username);
            stmt.setString(3, password);
            stmt.setString(4, email);
            stmt.setString(5, role.toLowerCase());
            stmt.setString(6, nomorTelepon);
            stmt.setString(7, alamat);

            // Eksekusi query
            stmt.executeUpdate();

            // Tampilkan pesan sukses
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");

            // Refresh tabel
            tampilkanData();

            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data: " + ex.getMessage());
        }
    }//GEN-LAST:event_btntambahtuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindatauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindatauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindatauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindatauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindatauser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconD btndataadmin;
    private rojerusan.RSButtonIconD btnedituser;
    private rojerusan.RSButtonIconD btnhapustuser;
    private rojerusan.RSButtonIconD btntambahtuser;
    private javax.swing.JLabel exit15;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel mainpanel;
    private efectos.MaterialColor materialColor1;
    private javax.swing.JPanel pnback;
    private rojerusan.RSButtonIconD rSButtonIconD2;
    private javax.swing.JTable tabeluser;
    // End of variables declaration//GEN-END:variables
}
